name: Test ray and fail

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-ray:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ray-version: ["2.40.0", "2.39.0", "2.38.0", "2.37.0", "2.36.0", "2.35.0", "2.34.0", "2.33.0", "2.32.0", "2.31.0", "2.30.0",  "2.24.0", "2.23.0", "2.22.0", "2.21.0", "2.20.0",  "2.12.0", "2.11.0", "2.10.0", "2.9.0", "2.8.0", "2.7.0", "2.6.0", "2.5.0", "2.4.0", "2.3.0", "2.2.0", "2.1.0", "2.0.0"]
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup ray
        run: |
          pip install -U "ray[default]==${{ matrix.ray-version }}"

      - name: Run the ray script
        run: |
          python emoji.py
